[project]
name = "notion-backup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dilawar Singh", email = "dilawar.s.rajput@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.5",
]

[project.scripts]
notion-backup = "notion_backup:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
